<?php

namespace api\models;

use Yii;

class Conhisd extends \yii\db\ActiveRecord
{
	
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vod_RoomHisFeeD';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbvodsy');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Serial', 'BH'], 'required'],
            [['Serial', 'Name', 'ZengPin', 'JSStyle', 'inXiaoFei', 'PrintID', 'Worker', 'zsr', 'ChuPin', 'tjlx', 'DanWei', 'waiter', 'vTime', 'RoomName', 'ProcHost', 'SaleMan', 'BZ', 'ProcTime'], 'string'],
            [['BH', 'RoomID', 'FeeStyle', 'Rebate', 'AllowRebate', 'Flag', 'FoodID'], 'integer'],
            [['Price', 'Num', 'CountF', 'PriceY'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Serial' => 'Serial',
            'BH' => 'Bh',
            'RoomID' => 'Room ID',
            'FeeStyle' => 'Fee Style',
            'Name' => 'Name',
            'Price' => 'Price',
            'Num' => 'Num',
            'Rebate' => 'Rebate',
            'CountF' => 'Count F',
            'AllowRebate' => 'Allow Rebate',
            'Flag' => 'Flag',
            'ZengPin' => 'Zeng Pin',
            'JSStyle' => 'Jsstyle',
            'inXiaoFei' => 'In Xiao Fei',
            'PrintID' => 'Print ID',
            'Worker' => 'Worker',
            'zsr' => 'Zsr',
            'ChuPin' => 'Chu Pin',
            'tjlx' => 'Tjlx',
            'DanWei' => 'Dan Wei',
            'waiter' => 'Waiter',
            'FoodID' => 'Food ID',
            'vTime' => 'V Time',
            'RoomName' => 'Room Name',
            'ProcHost' => 'Proc Host',
            'SaleMan' => 'Sale Man',
            'BZ' => 'Bz',
            'PriceY' => 'Price Y',
            'ProcTime' => 'Proc Time',
        ];
    }
    
    public static function primaryKey()
    {
    	return ['Serial']; // TODO: Change the autogenerated stub
    }
}
