<?php

namespace api\models;

use Yii;

class VipMember extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vip_Member';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbvodsy');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'JF', 'LJJF', 'ZK', 'XFCS', 'rqKind'], 'integer'],
            [['KH', 'YKH', 'XKH', 'MM', 'KL', 'KJ', 'KFRQ', 'SCXF', 'ZT', 'YXQ', 'KBZ', 'XM', 'XB', 'CSRQ', 'DW', 'YDDH', 'GDDH', 'DZYJ', 'ZJLX', 'ZJHM', 'LXDZ', 'SSXZ', 'SSSX', 'SSGJ', 'SSDQ', 'JSR', 'SG', 'TZ', 'CPHM', 'GRAH', 'BZ', 'JFQL', 'cyjf', 'kkh', 'csrq2', 'CurDay', 'kh_1', 'kh_2', 'kh_3', 'kh_4', 'kh_5'], 'string'],
            [['JE', 'ljck', 'JE1', 'OpenJE', 'OpenJE1', 'OpenJE0'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'KH' => 'Kh',
            'YKH' => 'Ykh',
            'XKH' => 'Xkh',
            'MM' => 'Mm',
            'KL' => 'Kl',
            'KJ' => 'Kj',
            'JF' => 'Jf',
            'LJJF' => 'Ljjf',
            'ZK' => 'Zk',
            'JE' => 'Je',
            'ljck' => 'Ljck',
            'XFCS' => 'Xfcs',
            'KFRQ' => 'Kfrq',
            'SCXF' => 'Scxf',
            'ZT' => 'Zt',
            'YXQ' => 'Yxq',
            'KBZ' => 'Kbz',
            'XM' => 'Xm',
            'XB' => 'Xb',
            'CSRQ' => 'Csrq',
            'DW' => 'Dw',
            'YDDH' => 'Yddh',
            'GDDH' => 'Gddh',
            'DZYJ' => 'Dzyj',
            'ZJLX' => 'Zjlx',
            'ZJHM' => 'Zjhm',
            'LXDZ' => 'Lxdz',
            'SSXZ' => 'Ssxz',
            'SSSX' => 'Sssx',
            'SSGJ' => 'Ssgj',
            'SSDQ' => 'Ssdq',
            'JSR' => 'Jsr',
            'SG' => 'Sg',
            'TZ' => 'Tz',
            'CPHM' => 'Cphm',
            'GRAH' => 'Grah',
            'BZ' => 'Bz',
            'JFQL' => 'Jfql',
            'cyjf' => 'Cyjf',
            'kkh' => 'Kkh',
            'rqKind' => 'Rq Kind',
            'csrq2' => 'Csrq2',
            'CurDay' => 'Cur Day',
            'JE1' => 'Je1',
            'OpenJE' => 'Open Je',
            'OpenJE1' => 'Open Je1',
            'OpenJE0' => 'Open Je0',
            'kh_1' => 'Kh 1',
            'kh_2' => 'Kh 2',
            'kh_3' => 'Kh 3',
            'kh_4' => 'Kh 4',
            'kh_5' => 'Kh 5',
        ];
    }
    
    public static function primaryKey()
    {
    	return ['id']; // TODO: Change the autogenerated stub
    }
}
